Fix ValueError for empty buffer in EsStore
If the buffer is empty, the following exception is raised in the done
method of EsStore.

    ValueError: Empty value passed for a required argument 'body'.