Handle cloud errors in AzureCloud
Some subscriptions in Azure could result in the following exception at
line 123 in cloudmarker/clouds/azurecloud.py while iterating over the
objects of any specified Azure provider.

    msrestazure.azure_exceptions.CloudError: Azure Error:
    DisallowedOperation
    Message: The current subscription type is not permitted to perform
    operations on any provider namespace. Please use a different
    subscription.

This commit aims to catch these exceptions and handle them gracefully
by letting the code continue reading documents from other Azure
subscriptions instead of exiting when any subscription throws the above
exception.